### ISSUE TITLE
IP forward

### ISSUE THREAD

**Issue by LiannOM** [bilintsui/minecraft-relay-server#7]
Hey could you make feature that allow bungeecord catch real player ip instead of relay server ip?

My servers structure:

Relay server (proxy) > BungeeCord Server > Lobby Server

When user is connected thro relay server to bungee and then to lobby his ip is relay's server ip not his own, Is there any fix for that or something?

**Comment by LiannOM** [comment]
Its very important please !!!!

**Comment by bilintsui** [comment]
Technically hard to do it currently.
Because the forwarding framework is working on the Application Layer (OSI), which means the proxy server don't provide any address & port information to the target server itself. The actual information is provided by system automatically.
In case of connecting to Bungeecord, this proxy server actually act as a client. So, the IP & port shown at BC is the IP & port of the proxy server itself. That's why the problem comes.
But if BC provides API about that, it's possibile to add that feature.

**Comment by LiannOM** [comment]
Can you describe more about that api ? or have any other idea how to make it work even without mcrelay server ?

**Comment by bilintsui** [comment]
I said "IF BC PROVIDES API", I currently don't know if such an API exists.
For solution without mcrelay server, you need to expose your BC to Internet. For more, please see BC's document.

**Comment by LiannOM** [comment]
I Already have bc server thats why i want to hide its real ip under mcrelay server...

**Comment by bilintsui** [comment]
Currently no solution about the problem you described. You can use mcrelay's log to see player's address & port when logging instead.
I will close this issue now, and reopen it when I find some solution.

**Comment by bilintsui** [comment]
It can implemented through "proxy protocol", but this feature will come after a complete config format revamp(planned change).

**Comment by LiannOM** [comment]
Wow that would be really awesome thing mate!

sob., 4 wrz 2021, 18:56 użytkownik Bilin Tsui ***@***.***>
napisał:

**Comment by bilintsui** [comment]
Added, see v1.2-beta1-patch10.
